// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2aq_c7Q5TUStTdP8IvYHpE-3o5_T-bs',
    appId: '1:11389642457:web:f2686cd397f98c261b00c8',
    messagingSenderId: '11389642457',
    projectId: 'drawing-app-56ed1',
    authDomain: 'drawing-app-56ed1.firebaseapp.com',
    storageBucket: 'drawing-app-56ed1.firebasestorage.app',
    measurementId: 'G-D5LWXG43SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiKY34LOhHmoewx6FaDZTR9mZ3McPsUE',
    appId: '1:11389642457:android:3677b94c344019011b00c8',
    messagingSenderId: '11389642457',
    projectId: 'drawing-app-56ed1',
    storageBucket: 'drawing-app-56ed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXiFwPBPBEzPy3XtjqhN543wEmuc2pZvY',
    appId: '1:11389642457:ios:a722ca11355f4ddd1b00c8',
    messagingSenderId: '11389642457',
    projectId: 'drawing-app-56ed1',
    storageBucket: 'drawing-app-56ed1.firebasestorage.app',
    iosBundleId: 'com.example.test001',
  );
}
